
/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractInstanceWithAddress, type ContractMethod, type ContractStorageLayout, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import NocomLendingPoolV1ContractArtifactJson from './NocomLendingPool.json' with { type: 'json' };
export const NocomLendingPoolV1ContractArtifact = loadContractArtifact(NocomLendingPoolV1ContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract NocomLendingPoolV1;
 */
export class NocomLendingPoolV1Contract extends ContractBase {
  
  private constructor(
    instance: ContractInstanceWithAddress,
    wallet: Wallet,
  ) {
    super(instance, NocomLendingPoolV1ContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A promise that resolves to a new Contract instance.
   */
  public static async at(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    return Contract.at(address, NocomLendingPoolV1Contract.artifact, wallet) as Promise<NocomLendingPoolV1Contract>;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, admin_address: AztecAddressLike, liquidator_pubkey_x: FieldLike, liquidator_pubkey_y: FieldLike, price_oracle_address: AztecAddressLike, treasury_address: AztecAddressLike, collateral_token_address: AztecAddressLike, loaned_token_address: AztecAddressLike, max_ltv: (bigint | number), liquidation_threshold: (bigint | number)) {
    return new DeployMethod<NocomLendingPoolV1Contract>(PublicKeys.default(), wallet, NocomLendingPoolV1ContractArtifact, NocomLendingPoolV1Contract.at, Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, admin_address: AztecAddressLike, liquidator_pubkey_x: FieldLike, liquidator_pubkey_y: FieldLike, price_oracle_address: AztecAddressLike, treasury_address: AztecAddressLike, collateral_token_address: AztecAddressLike, loaned_token_address: AztecAddressLike, max_ltv: (bigint | number), liquidation_threshold: (bigint | number)) {
    return new DeployMethod<NocomLendingPoolV1Contract>(publicKeys, wallet, NocomLendingPoolV1ContractArtifact, NocomLendingPoolV1Contract.at, Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof NocomLendingPoolV1Contract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<NocomLendingPoolV1Contract['methods'][M]>
  ) {
    return new DeployMethod<NocomLendingPoolV1Contract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      NocomLendingPoolV1ContractArtifact,
      NocomLendingPoolV1Contract.at,
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return NocomLendingPoolV1ContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(NocomLendingPoolV1ContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'config' | 'collateral' | 'loan' | 'debt' | 'utilization'> {
      return {
        config: {
      slot: new Fr(1n),
    },
collateral: {
      slot: new Fr(11n),
    },
loan: {
      slot: new Fr(12n),
    },
debt: {
      slot: new Fr(13n),
    },
utilization: {
      slot: new Fr(14n),
    }
      } as ContractStorageLayout<'config' | 'collateral' | 'loan' | 'debt' | 'utilization'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** borrow_private(recipient: struct, amount: integer, partial_note: field, asserted_collateral_token_price: integer, asserted_loaned_token_price: integer) */
    borrow_private: ((recipient: AztecAddressLike, amount: (bigint | number), partial_note: FieldLike, asserted_collateral_token_price: (bigint | number), asserted_loaned_token_price: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** collateralize_private(from: struct, amount: integer, authwit_nonce: field) */
    collateralize_private: ((from: AztecAddressLike, amount: (bigint | number), authwit_nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** constructor(admin_address: struct, liquidator_pubkey_x: field, liquidator_pubkey_y: field, price_oracle_address: struct, treasury_address: struct, collateral_token_address: struct, loaned_token_address: struct, max_ltv: integer, liquidation_threshold: integer) */
    constructor: ((admin_address: AztecAddressLike, liquidator_pubkey_x: FieldLike, liquidator_pubkey_y: FieldLike, price_oracle_address: AztecAddressLike, treasury_address: AztecAddressLike, collateral_token_address: AztecAddressLike, loaned_token_address: AztecAddressLike, max_ltv: (bigint | number), liquidation_threshold: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_collateral_and_debt(borrower: struct) */
    get_collateral_and_debt: ((borrower: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_config() */
    get_config: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_health_factor(borrower: struct, next_epoch: integer, asserted_collateral_token_price: integer, asserted_loaned_token_price: integer) */
    get_health_factor: ((borrower: AztecAddressLike, next_epoch: (bigint | number), asserted_collateral_token_price: (bigint | number), asserted_loaned_token_price: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_loan(lender: struct) */
    get_loan: ((lender: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_utilization() */
    get_utilization: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** liquidate_private(amount_to_repay: integer, liquidator_address: struct, liquidation_authwit_nonce: field, liquidator_partial_note: field, asserted_collateral_token_price: integer, asserted_loaned_token_price: integer) */
    liquidate_private: ((amount_to_repay: (bigint | number), liquidator_address: AztecAddressLike, liquidation_authwit_nonce: FieldLike, liquidator_partial_note: FieldLike, asserted_collateral_token_price: (bigint | number), asserted_loaned_token_price: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** process_message(message_ciphertext: struct, message_context: struct) */
    process_message: ((message_ciphertext: FieldLike[], message_context: { tx_hash: FieldLike, unique_note_hashes_in_tx: FieldLike[], first_nullifier_in_tx: FieldLike, recipient: AztecAddressLike }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** register(signature: array) */
    register: ((signature: (bigint | number)[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** repay_loan_private(from: struct, amount: integer, authwit_nonce: field) */
    repay_loan_private: ((from: AztecAddressLike, amount: (bigint | number), authwit_nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** supply_private(from: struct, amount: integer, authwit_nonce: field) */
    supply_private: ((from: AztecAddressLike, amount: (bigint | number), authwit_nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_private_state() */
    sync_private_state: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** withdraw_collateral_private(amount: integer, recipient: struct, partial_note: field, asserted_collateral_token_price: integer, asserted_loaned_token_price: integer) */
    withdraw_collateral_private: ((amount: (bigint | number), recipient: AztecAddressLike, partial_note: FieldLike, asserted_collateral_token_price: (bigint | number), asserted_loaned_token_price: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** withdraw_loan_private(amount: integer, recipient: struct, partial_note: field) */
    withdraw_loan_private: ((amount: (bigint | number), recipient: AztecAddressLike, partial_note: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
