// Default Configuration Constants
export const DEFAULT_PRICE_UPDATE_INTERVAL = 60000; // 60 seconds
export const DEFAULT_PRICE_CHANGE_THRESHOLD = 0.5; // 0.5%
export const DEFAULT_MAX_UPDATE_INTERVAL = 1800000; // 30 minutes
export const DEFAULT_MAX_TRACKED_ASSETS = 50;
export const DEFAULT_SYNC_INTERVAL = 60000; // 60 seconds (1 minute)

// API Port Defaults
export const DEFAULT_PRICE_SERVICE_PORT = 3000;
export const DEFAULT_NOTE_MONITOR_PORT = 3001;
export const DEFAULT_LIQUIDATION_ENGINE_PORT = 3002;

// Mock Values (for Phase 1-7 implementation)
export const MOCK_INTEREST_RATE = 0.05; // 5% APR
export const MOCK_COLLATERALIZATION_THRESHOLD = 1.5; // 150%
export const MOCK_LIQUIDATION_BONUS = 0.05; // 5% bonus for liquidator

// Error Codes
export const ERROR_CODES = {
  INVALID_REQUEST: 'INVALID_REQUEST',
  ASSET_NOT_FOUND: 'ASSET_NOT_FOUND',
  ASSET_ALREADY_TRACKED: 'ASSET_ALREADY_TRACKED',
  MAX_ASSETS_REACHED: 'MAX_ASSETS_REACHED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  PRICE_FETCH_FAILED: 'PRICE_FETCH_FAILED',
  ESCROW_NOT_FOUND: 'ESCROW_NOT_FOUND',
  PXE_CONNECTION_FAILED: 'PXE_CONNECTION_FAILED',
  LIQUIDATION_FAILED: 'LIQUIDATION_FAILED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

// HTTP Status Codes
export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  NOT_FOUND: 404,
  CONFLICT: 409,
  INTERNAL_SERVER_ERROR: 500,
} as const;
