
/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractInstanceWithAddress, type ContractMethod, type ContractStorageLayout, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import NocomEscrowV1ContractArtifactJson from './NocomEscrow.json' with { type: 'json' };
export const NocomEscrowV1ContractArtifact = loadContractArtifact(NocomEscrowV1ContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract NocomEscrowV1;
 */
export class NocomEscrowV1Contract extends ContractBase {
  
  private constructor(
    instance: ContractInstanceWithAddress,
    wallet: Wallet,
  ) {
    super(instance, NocomEscrowV1ContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A promise that resolves to a new Contract instance.
   */
  public static async at(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    return Contract.at(address, NocomEscrowV1Contract.artifact, wallet) as Promise<NocomEscrowV1Contract>;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, pool_address: AztecAddressLike, collateral_token_address: AztecAddressLike, loaned_token_address: AztecAddressLike) {
    return new DeployMethod<NocomEscrowV1Contract>(PublicKeys.default(), wallet, NocomEscrowV1ContractArtifact, NocomEscrowV1Contract.at, Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, pool_address: AztecAddressLike, collateral_token_address: AztecAddressLike, loaned_token_address: AztecAddressLike) {
    return new DeployMethod<NocomEscrowV1Contract>(publicKeys, wallet, NocomEscrowV1ContractArtifact, NocomEscrowV1Contract.at, Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof NocomEscrowV1Contract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<NocomEscrowV1Contract['methods'][M]>
  ) {
    return new DeployMethod<NocomEscrowV1Contract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      NocomEscrowV1ContractArtifact,
      NocomEscrowV1Contract.at,
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return NocomEscrowV1ContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(NocomEscrowV1ContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'config'> {
      return {
        config: {
      slot: new Fr(1n),
    }
      } as ContractStorageLayout<'config'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** borrow(amount: integer, asserted_collateral_token_price: integer, asserted_debt_token_price: integer) */
    borrow: ((amount: (bigint | number), asserted_collateral_token_price: (bigint | number), asserted_debt_token_price: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** constructor(pool_address: struct, collateral_token_address: struct, loaned_token_address: struct) */
    constructor: ((pool_address: AztecAddressLike, collateral_token_address: AztecAddressLike, loaned_token_address: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_config() */
    get_config: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** liquidate(amount: integer, liquidation_authwit_nonce: field, asserted_collateral_token_price: integer, asserted_debt_token_price: integer) */
    liquidate: ((amount: (bigint | number), liquidation_authwit_nonce: FieldLike, asserted_collateral_token_price: (bigint | number), asserted_debt_token_price: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** process_message(message_ciphertext: struct, message_context: struct) */
    process_message: ((message_ciphertext: FieldLike[], message_context: { tx_hash: FieldLike, unique_note_hashes_in_tx: FieldLike[], first_nullifier_in_tx: FieldLike, recipient: AztecAddressLike }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** register(signature: array) */
    register: ((signature: (bigint | number)[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** repay(amount: integer, authwit_nonce: field) */
    repay: ((amount: (bigint | number), authwit_nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** supply_collateral(amount: integer, authwit_nonce: field) */
    supply_collateral: ((amount: (bigint | number), authwit_nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_private_state() */
    sync_private_state: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** withdraw_collateral(amount: integer, asserted_collateral_token_price: integer, asserted_loaned_token_price: integer) */
    withdraw_collateral: ((amount: (bigint | number), asserted_collateral_token_price: (bigint | number), asserted_loaned_token_price: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
